### ISSUE TITLE
Translate the docs / Stability

### ISSUE THREAD

**Issue by Fuzzyma** [aprezcuba24/CULabsIlluminateBundle#1]
Thanks for your effort to make Illuminate available as symfony bundle.
Is there any chance, that you can write english docs? It would makes thinks easier.

Furthermore: How stable is this code? I saw, that there is no release yet. Any chance that this will happen soon?

**Comment by aprezcuba24** [comment]
Hi Fuzzyma, my english is very bad and i can't translate the doc. I make this bundle for use it in own projects, but i please to help you if you want use it. The Queue and Schedule is the only thing implemented. If you want, you cant write me to my email aprezcuba24@gmail.com

**Comment by aprezcuba24** [comment]
I am pleased to help you. You may write me if you want.

**Comment by Fuzzyma** [comment]
I found this https://github.com/WouterJ/WouterJEloquentBundle which wuite good covers my needs :)

**Comment by aprezcuba24** [comment]
I am glad for you. In the close future i will to make the english's doc. I have seen the WouterJEloquentBundle and it has other object. My bundle is only for Queue and Schedule.
If you want other things, write me.
